---
contests:
- US president:
    tally: rcv
    choices:
    - name: Circle Party Ticket
      ticket_names:
        - Rey Skywalker
        - Obi-Wan Kenobi
      ticket_offices:
        - President
        - Vice President
    - name: Square Party Ticket
      ticket_names:
        - Atticus Finch
        - Forrest Gump
      ticket_offices:
        - President
        - Vice President
    - name: Triangle Party Ticket
      ticket_names:
        - Evelyn Quan Wang
        - Waymond Wang
      ticket_offices:
        - President
        - Vice President
- US senate:
    tally: rcv
    choices:
    - name: Fred Flintstone
      party: Circle Party
    - name: Shrek
      party: Square Party
    - name: Mirabel Madrigal
      party: Triangle Party
- governor:
    tally: plurality
    choices:
    - name: Hermione Granger
      party: Circle Party
    - name: Gandalf
      party: Triangle Party
GGOs:
  counties:
  - Middlesex
  towns:
  - Concord
submodules: []
